import { fieldSchema, type Field, type TemplateType } from './schemas';
type Definition = [string, string, Field['dataType'], string[]?];
const definitions: Record<TemplateType, Definition[]> = {
  apartments: [
    ['name', 'Property', 'text'],
    ['address', 'Address', 'text'],
    ['rent', 'Monthly rent', 'currency'],
    ['bedrooms', 'Bedrooms', 'number'],
    ['bathrooms', 'Bathrooms', 'number'],
    ['square_feet', 'Square feet', 'number'],
    ['utilities', 'Utilities included', 'text'],
    ['parking', 'Parking', 'boolean'],
    ['parking_cost', 'Parking cost', 'currency'],
    ['laundry', 'Laundry', 'text'],
    ['furnished', 'Furnished', 'boolean'],
    ['pets', 'Pets', 'text'],
    ['gym', 'Gym', 'boolean'],
    ['pool', 'Pool', 'boolean'],
    ['lease_term', 'Lease term', 'text'],
    ['deposit', 'Deposit', 'currency'],
  ],
  hotels: [
    ['name', 'Hotel', 'text'],
    ['location', 'Location', 'text'],
    ['nightly_rate', 'Nightly rate', 'currency'],
    ['total_price', 'Total stay price', 'currency'],
    ['rating', 'Rating', 'number'],
    ['pool', 'Pool', 'boolean'],
    ['gym', 'Gym', 'boolean'],
    ['breakfast', 'Breakfast', 'text'],
    ['parking', 'Parking', 'boolean'],
    ['parking_cost', 'Parking cost', 'currency'],
    ['resort_fee', 'Resort fee', 'currency'],
    ['shuttle', 'Airport shuttle', 'boolean'],
    ['cancellation', 'Cancellation policy', 'text'],
  ],
  jobs: [
    ['company', 'Company', 'text'],
    ['role', 'Role', 'text'],
    ['location', 'Location', 'text'],
    ['workplace', 'Workplace', 'enum', ['Remote', 'Hybrid', 'On-site']],
    ['salary', 'Salary', 'text'],
    ['employment_type', 'Employment type', 'text'],
    ['term', 'Term length', 'text'],
    ['deadline', 'Deadline', 'date'],
    ['requirements', 'Requirements', 'list'],
    ['skills', 'Skills', 'list'],
    ['authorization', 'Work authorization', 'text'],
    ['application_url', 'Application URL', 'url'],
  ],
  products: [
    ['name', 'Product', 'text'],
    ['brand', 'Brand', 'text'],
    ['price', 'Price', 'currency'],
    ['specs', 'Specifications', 'list'],
    ['rating', 'Rating', 'number'],
    ['warranty', 'Warranty', 'text'],
    ['shipping', 'Shipping', 'text'],
  ],
  cars: [
    ['make', 'Make', 'text'],
    ['model', 'Model', 'text'],
    ['year', 'Year', 'number'],
    ['price', 'Price', 'currency'],
    ['mileage', 'Mileage', 'number'],
    ['drivetrain', 'Drivetrain', 'text'],
    ['accidents', 'Accident information', 'text'],
    ['seller', 'Seller', 'text'],
    ['features', 'Features', 'list'],
  ],
  courses: [
    ['institution', 'Institution', 'text'],
    ['program', 'Program', 'text'],
    ['tuition', 'Tuition', 'currency'],
    ['duration', 'Duration', 'text'],
    ['location', 'Location', 'text'],
    ['prerequisites', 'Prerequisites', 'list'],
    ['deadline', 'Deadline', 'date'],
    ['format', 'Delivery format', 'text'],
  ],
  custom: [['name', 'Name', 'text']],
};
export const templateLabels: Record<TemplateType, string> = {
  apartments: 'Apartments',
  hotels: 'Hotels',
  jobs: 'Jobs',
  products: 'Products',
  cars: 'Cars',
  courses: 'Courses / Programs',
  custom: 'Custom',
};
export function createFields(template: TemplateType): Field[] {
  return definitions[template].map(
    ([key, label, dataType, enumOptions], position) =>
      fieldSchema.parse({
        id: crypto.randomUUID(),
        key,
        label,
        dataType,
        enumOptions: enumOptions ?? [],
        position,
      }),
  );
}
